### ISSUE TITLE
rename curry function

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/chickencurry#10]
How about we rename the `curry` function into `curried`?

```js
const {curried, _} = require('curry-this');


// Got a simple function?

const plus = (a, b, c) => a + b + c;
const plusThree = plus::curried(3);
```

**Comment by tomekwi** [comment]
I think it would be good when the whole module was named like this.

But look at native JS functions and **[trine](https://github.com/jussi-kalliokoski/trine)**. All functions are just infinitive verbs: `map`, `split`, `filter`, …

**Comment by stoeffel** [comment]
Good point. Let's keep `curry`
