### ISSUE TITLE
Move to ESLint

### ISSUE THREAD

**Issue by tomekwi** [stoeffel/chickencurry#13]
JSHint chokes on function bind syntax:

```
$ git checkout 357db73
$ ./node_modules/.bin/jshint test/es6.js 
test/es6.js: line 13, col 26, Missing semicolon.
test/es6.js: line 13, col 26, Expected '}' to match '{' from line 12 and instead saw ':'.
test/es6.js: line 13, col 27, Expected ')' and instead saw ':'.
test/es6.js: line 13, col 28, Missing semicolon.
test/es6.js: line 39, col 1, Unrecoverable syntax error. (63% scanned).

5 errors
```

@stoeffel do you have experience with [ESLint](http://eslint.org/)? I’ve heard good opinions.

**Comment by IanVS** [comment]
Hi, I'd be happy to help answer any questions you've got about ESLint.

**Comment by stoeffel** [comment]
eslint doesn't support `function bind syntax` refs #https://github.com/eslint/eslint/issues/2728
But maybe there is a plugin for that.

@IanVS Thanks, do you know a plugin to allow `function bind syntax` (f.e. `func::curry(1, 2)`)?

**Comment by stoeffel** [comment]
let's try https://github.com/babel/babel-eslint

**Comment by tomekwi** [comment]
Done! There’s a fair share of warnings there, by the way: <https://travis-ci.org/stoeffel/chickencurry/jobs/73223568>.

**Comment by IanVS** [comment]
Sorry, I'm not aware of any such plugins.

The warnings ESLint generates initially can be a little overwhelming.  I wrote [eslint-nibble](https://github.com/IanVS/eslint-nibble) to try to make it a little easier to chip away and fix the errors.  It will give you an overview of how many errors there are across all of your project, grouped by rule, and then allow you to focus in on one rule at a time.  Maybe it will be helpful to you.

**Comment by tomekwi** [comment]
Thanks @IanVS, it’s much better now: <https://travis-ci.org/stoeffel/chickencurry/jobs/73225562>. Your program looks good. At the moment I’m quite happy with my setup: https://atom.io/ + https://atom.io/packages/linter + <https://atom.io/packages/linter-eslint> – but I’ll try the nibble thing out when I’m in for something new.

**Comment by tomekwi** [comment]
> Sorry, I'm not aware of any such plugins.

*babel-eslint* does a good job so far.

**Comment by tomekwi** [comment]
> Thanks @IanVS, it’s much better now: https://travis-ci.org/stoeffel/chickencurry/jobs/73225562.

Ooops, it’s not. It looked good on my dev machine, but it seems like it lints transpiled files on Travis. Hmm, does that mean that *eslint* ignores the [`--ignore-path .gitignore`](https://github.com/stoeffel/chickencurry/blob/abc6f2a3f7a753096066ac8fd15df679f6ec7606/package.json#L12) option we’ve specified? I’ve got the same problems after `npm run`ning `transpile`.

Have you run into similar problems @IanVS?

**Comment by IanVS** [comment]
I wonder if this has to do with https://github.com/eslint/eslint/issues/1862.  Perhaps the `*.js` is not being applied correctly?  Maybe you could try changing the `.gitignore` to `./*.js` as an experiment.

**Comment by stoeffel** [comment]
> Have you run into similar problems @IanVS?

It's the same on my machine.

**Comment by stoeffel** [comment]
> Maybe you could try changing the .gitignore to ./*.js as an experiment.

This worked! Thanks.

//cc @IanVS

**Comment by tomekwi** [comment]
Thanks @stoeffel. I just wonder if `/*.js` and `./*.js` means the same to git. That could be quite an important difference.

**Comment by tomekwi** [comment]
Alright, it does seem to mean the same:

![image](https://cloud.githubusercontent.com/assets/4624660/8965093/9220ab1a-3629-11e5-904a-aa16d82d77fc.png)

**Comment by stoeffel** [comment]
> Alright, it does seem to mean the same:

Yop. I think it's `/*.js` in the root of your machine and `./*.js` in the root of the repo

**Comment by tomekwi** [comment]
Actually, no. I was wrong. `./*.js` excludes all nested files as well:

![image](https://cloud.githubusercontent.com/assets/4624660/8965198/3b1112d2-362a-11e5-9a17-2215528e6b6c.png)

**Comment by tomekwi** [comment]
>  I think it's /*.js in the root of your machine and ./*.js in the root of the repo

`/*.js` is the root of the repo. See <http://git-scm.com/docs/gitignore>.

**Comment by IanVS** [comment]
> Actually, no. I was wrong.  ./*.js  excludes all nested files as well:

What does your .gitignore look like?

**Comment by tomekwi** [comment]
`./*.js` doesn’t ignore JS files at all:

![image](https://cloud.githubusercontent.com/assets/4624660/8965284/c44709f8-362a-11e5-8017-4a95f8bf9e34.png)

**Comment by tomekwi** [comment]
> What does your .gitignore look like?

https://github.com/stoeffel/chickencurry/blob/1a7cd601e734d60a0b433dcb9ebcd7d6beacd506/.gitignore

**Comment by IanVS** [comment]
Strange.  Maybe this is a case where it would be best to just create a `.eslintignore` file and not worry about the weird inconsistencies between `.gitignore` and ESLint.

**Comment by tomekwi** [comment]
Yeah, maybe you’re right. I managed to fix this temporarily at @c6b5b8e .

**Comment by tomekwi** [comment]
Thanks for pointing us in the right direction though @IanVS!

**Comment by IanVS** [comment]
No problem. Feel free to submit an issue in ESLint if you think docs or behavior could be improved.
