### ISSUE TITLE
ES 2016 tests fail

### ISSUE THREAD

**Issue by tomekwi** [stoeffel/chickencurry#15]
@stoeffel could you please have a look at the [failing tests](https://travis-ci.org/stoeffel/chickencurry/jobs/73228219#L343-L377)? Is there something wrong with [my specs](https://github.com/stoeffel/chickencurry/blob/fb459ad842706255891a4548640bea7968725f9f/test/es-2016.js#L10-L60)?

**Comment by stoeffel** [comment]
@tomekwi I will check it out.

**Comment by stoeffel** [comment]
found it. one moment.

**Comment by stoeffel** [comment]
fixed in https://github.com/stoeffel/chickencurry/commit/00a11f61026710401b58c5eb30f02274ae0c4386
