### ISSUE TITLE
logo for v3

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/chickencurry#16]
Would be cool.

**Comment by stoeffel** [comment]
@tomekwi how do you like the logo?

**Comment by tomekwi** [comment]
Wow! Nice :)

Though it does look blurry and deformed in the readme:

![image](https://cloud.githubusercontent.com/assets/4624660/9032647/df613274-39c0-11e5-813c-c520171d979f.png)

– as opposed to the PNG itself:

![image](https://cloud.githubusercontent.com/assets/4624660/9032653/f71cad9e-39c0-11e5-8a63-5e59b5dc82c0.png)

– and that on a standard-resolution screen. It’d be worse on a retina. Have you thought about using a PNG for the logo?

**Comment by stoeffel** [comment]
> Though it does look blurry and deformed in the readme:

I removed the `width` and `height` from the image tag. It looks better on my retina. For you?

**Comment by tomekwi** [comment]
:+1:
