### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by tomekwi** [stoeffel/chickencurry#6]
Hi @stoeffel I liked the name *chickencurry* from the very beginning :D But TBH I don’t think it tells much about the module.

How about renaming to one of these:

* *modern-curry*
* *curry-bind*
* *curried* (would go well with the function bind syntax: `add::curried(5)` – the name is [taken](http://npm.im/curried) but the lib doesn’t look like it’s used or maintained)

– or perhaps another idea of yours?

Feel free to say “no, I like the current name” BTW.

**Comment by stoeffel** [comment]
> I don’t think it tells much about the module.

True...

`modern-curry` :-1: 
`curry-bind` :-1: 
`curried` :+1: we would have to contact the owner of `curried`

I'm totally open to other ideas (can't come up with a good one atm)

**Comment by stoeffel** [comment]
How about `curry-this` or `curry-it`?

**Comment by tomekwi** [comment]
`curry-this` :+1:

Good one!

**Comment by stoeffel** [comment]
Yop, I think we go with `curry-this`.
