### ISSUE TITLE
Design decisions

### ISSUE THREAD

**Issue by tomekwi** [stoeffel/chickencurry#7]
IMO it would be great when we married these:

* [dead simple API](https://github.com/stoeffel/chickencurry/tree/d01dce328ee90b66a27be564e258eb440775f4e1#curry-chickencurry) – only `curry` and `_`
* no dependencies
* make use of cutting-edge features

How to marry the two latter?

Say we’d like to use `Symbol`. We can’t use the global because that would require users to pull in a global polyfill (that’s a Bad Thing ®). 

My suggestion:

```js
// Pass an implementation:
const {curry, _} = require('curry-this')({
  Symbol: require('es6-symbol'),
});

// …or use a global in a modern environment:
const {curry, _} = require('curry-this');
```

I guess it’s possible and not that hard. But I may be wrong.

**Comment by stoeffel** [comment]
This all SGTM. Let's go for it.

**Comment by stoeffel** [comment]
refs #4

**Comment by tomekwi** [comment]
It should be ready as of @e3a1c9e

in ES 2015+:

```js
import {_, curry} from 'curry-this/module';
```

earlier:

```js
const {_, curry} = require('curry-this')({Symbol: () => ({})});
```
